#!/bin/bash
case $1 in
-r)
        echo 5.15.0-52-generic
;;
-a)
        echo "Linux centos 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux"
;;
-v)
        echo "#58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022"
;;
-m)
        echo x86_64
;;
-p)
	echo x86_64
;;
-i)
	echo x86_64
;;
-s)
	echo Linux
;;
-o)
	echo "GNU/Linux"
;;
-n)
	echo centos
;;
esac

if [ -z $1 ]; then
	echo Linux
fi
